apiVersion: v1
kind: Service
metadata: 
 name: myapp-front-end-service
 namespace: myapp
 labels:
  environment: production

spec:
 type: ClusterIP
 ports:
  - targetPort: 80
    port: 80
 selector:
  app: myapp
  type: front-end

